name: Build OpenSilver App

env:
on:
  push:
    branches:
      - main
      - master
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
      - name: Install .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.*'
          include-prerelease: true
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build
        run: |
          msbuild OpenSilverNet7Pipeline.Browser\OpenSilverNet7Pipeline.Browser.csproj -restore